version: '2.2'
services:
  springboot-um:
    build:
      context: users/
      dockerfile: Dockerfile
    image: springboot-um-web
    ports:
      - "8080:8080"
    networks:
      - um-network

  notification:
    build:
      context: notification/
      dockerfile: Dockerfile
    image: sprintboot-um-notification
    ports:
      - "8087:8080"
    networks:
      - um-network

  fake_mail_server:
    image: gessnerfl/fake-smtp-server:latest
    ports:
      - "5080:5080"
      - "5025:5025"
      - "5081:5081"
    environment:
      - fakesmtp.authentication.username=umbot@boot.com
      - fakesmtp.authentication.password=umbot!@# 
    networks:
      - um-network
 
networks:
  um-network:
